---
kind: pipeline
type: docker
name: default

clone:
  depth: 50

steps:
  - name: lint
    image: golang:1.15
    commands:
      - make lint
  - name: test
    image: golang:1.15
    commands:
      - "go test -v -mod=vendor ./..."
      - "./integrationtest.sh"
